name: Линтер

on: [push]

jobs:
  lint:
    name: Run Linters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pylint pytest requests
      
      - name: Run Flake8
        run: |
          flake8 app.py test_api.py config.py --max-line-length=99 --extend-ignore=E203,W503
      
      - name: Run Pylint
        run: |
          pylint app.py test_api.py config.py --rcfile=pylint.yml

      - name: Run Tests
        run: |
          pytest --disable-warnings