name: Линтер

on: [push]

jobs:
  for_app:
    name: Для приложения
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Установка Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.0
      
      - name: Установка зависимостей
        run:  |
          python -m pip install --upgrade pip
          pip install flake8==3.9.0 wemake-python-styleguide==0.15.3 bandit==1.7.2
      
      - name: Запуск flake8
        working-directory: ./myproject
        run: flake8 app.py test_api.py config.py
  for_test:
        name: Запуск тестов
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - name: Установка Python
            uses: actions/setup-python@v2
            with:
              python-version: 3.11.0
          - name: Установка зависимостей
            run: |
              python -m pip install --upgrade pip
              pip install pytest==7.4.2
              pip install requests==2.31.0
              pip install Flask==3.0.2
          - name: Pytest
            working-directory: ./myproject
            run: pytest test_api.py